name: learning2write
dependencies:
  - python==3.7.3
  - numpy==1.16.4
  - pip
  - pip:
      - stable-baselines==2.6.0
      - python-mnist==0.6
      - plac==1.0.0
      - gym==0.13.1
      - tensorflow-gpu==1.14.0